"""
generate_deployment_bundle.py
Generates the Databricks Asset Bundle job resource definition from the real,
already-converted workflow_spec.json — never hand-transcribed, so the bundle
always reflects exactly what the SSIS conversion layer produced (81 tasks
today; re-run this after any change to run_ssis_conversion.py's output).

Writes:
    bundle/resources/wwi_daily_etl_main.job.yml

Usage:
    python deploy/generate_deployment_bundle.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
WORKFLOW_SPEC = ROOT / "output" / "workflow_spec.json"
RESOURCE_OUT = ROOT / "bundle" / "resources" / "wwi_daily_etl_main.job.yml"


def render_job_yaml(spec: dict) -> str:
    lines = [
        "# Generated by deploy/generate_deployment_bundle.py from output/workflow_spec.json",
        "# Do not hand-edit task definitions here — re-run the generator instead so this",
        "# file always matches what the SSIS conversion layer actually produced.",
        "resources:",
        "  jobs:",
        f"    {spec['name']}:",
        f"      name: {spec['name']}-${{bundle.target}}",
        f"      description: \"{spec['description']}\"",
        "      tags:",
        "        project: wwi-modernisation",
        "        managed_by: databricks-asset-bundle",
        "      schedule:",
        f"        quartz_cron_expression: \"{spec['schedule']['quartz_cron_expression']}\"",
        f"        timezone_id: \"{spec['schedule']['timezone_id']}\"",
        "        pause_status: ${var.job_pause_status}",
        "      email_notifications:",
        "        on_failure:",
        "          - ${var.alert_email}",
        "      max_concurrent_runs: 1",
        "      queue:",
        "        enabled: true",
        "      parameters:",
        "        - name: environment",
        "          default: ${bundle.target}",
        "        - name: catalog",
        "          default: ${var.catalog}",
        "      tasks:",
    ]
    for t in spec["tasks"]:
        lines.append(f"        - task_key: {t['task_key']}")
        lines.append(f"          description: \"{t['description']}\"")
        if t["depends_on"]:
            lines.append("          depends_on:")
            for d in t["depends_on"]:
                lines.append(f"            - task_key: {d['task_key']}")
        if t.get("sql_task"):
            lines.append("          sql_task:")
            lines.append("            warehouse_id: ${var.sql_warehouse_id}")
            lines.append("            file:")
            lines.append(f"              path: \"../../output/{t['sql_task']['file']['path']}\"")
            lines.append("            parameters:")
            lines.append("              catalog: ${var.catalog}")
        elif t.get("notebook_task"):
            lines.append("          notebook_task:")
            notebook_rel = t["notebook_task"]["notebook_path"].replace("./", "")
            lines.append(f"            notebook_path: \"../../output/{notebook_rel}\"")
            lines.append("            base_parameters:")
            for k, v in t["notebook_task"]["base_parameters"].items():
                lines.append(f"              {k}: \"{v}\"")
            lines.append("              catalog: ${var.catalog}")
            lines.append("          environment_key: wwi_serverless_env")
        lines.append(f"          max_retries: {t['max_retries']}")
        lines.append(f"          timeout_seconds: {t['timeout_seconds']}")
        lines.append("          retry_on_timeout: false")
    lines += [
        "      environments:",
        "        - environment_key: wwi_serverless_env",
        "          spec:",
        "            client: \"1\"",
        "            dependencies:",
        "              - delta-spark>=3.0.0",
    ]
    return "\n".join(lines)


def main() -> None:
    spec = json.loads(WORKFLOW_SPEC.read_text(encoding="utf-8"))
    yaml_text = render_job_yaml(spec)
    RESOURCE_OUT.parent.mkdir(parents=True, exist_ok=True)
    RESOURCE_OUT.write_text(yaml_text, encoding="utf-8")
    print(f"Wrote {RESOURCE_OUT.relative_to(ROOT)} ({len(spec['tasks'])} tasks)")


if __name__ == "__main__":
    main()
