"""
generate_deployment_bundle.py
Generates the Databricks Asset Bundle job resource YAML from the
workflow_spec.json produced by run_ssis_conversion.py.

Usage:
    python deploy/generate_deployment_bundle.py \\
        --input-path ./output \\
        --output-path ./bundle \\
        --env dev
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
# Legacy defaults kept so the file can still be imported by mcp/tools/generate_bundle.py
WORKFLOW_SPEC = ROOT / "output" / "workflow_spec.json"
RESOURCE_OUT  = ROOT / "bundle" / "resources" / "wwi_daily_etl_main.job.yml"


def render_job_yaml(spec: dict) -> str:
    lines = [
        "# Generated by deploy/generate_deployment_bundle.py from output/workflow_spec.json",
        "# Do not hand-edit task definitions here — re-run the generator instead so this",
        "# file always matches what the SSIS conversion layer actually produced.",
        "resources:",
        "  jobs:",
        f"    {spec['name']}:",
        f"      name: {spec['name']}-${{bundle.target}}",
        f"      description: \"{spec['description']}\"",
        "      tags:",
        "        project: wwi-modernisation",
        "        managed_by: databricks-asset-bundle",
        "      schedule:",
        f"        quartz_cron_expression: \"{spec['schedule']['quartz_cron_expression']}\"",
        f"        timezone_id: \"{spec['schedule']['timezone_id']}\"",
        "        pause_status: ${var.job_pause_status}",
        "      email_notifications:",
        "        on_failure:",
        "          - ${var.alert_email}",
        "      max_concurrent_runs: 1",
        "      queue:",
        "        enabled: true",
        "      parameters:",
        "        - name: environment",
        "          default: ${bundle.target}",
        "        - name: catalog",
        "          default: ${var.catalog}",
        "      tasks:",
    ]
    for t in spec["tasks"]:
        lines.append(f"        - task_key: {t['task_key']}")
        lines.append(f"          description: \"{t['description']}\"")
        if t["depends_on"]:
            lines.append("          depends_on:")
            for d in t["depends_on"]:
                lines.append(f"            - task_key: {d['task_key']}")
        if t.get("sql_task"):
            lines.append("          sql_task:")
            lines.append("            warehouse_id: ${var.sql_warehouse_id}")
            lines.append("            file:")
            lines.append(f"              path: \"../../output/{t['sql_task']['file']['path']}\"")
            lines.append("            parameters:")
            lines.append("              catalog: ${var.catalog}")
        elif t.get("notebook_task"):
            lines.append("          notebook_task:")
            notebook_rel = t["notebook_task"]["notebook_path"].replace("./", "")
            lines.append(f"            notebook_path: \"../../output/{notebook_rel}\"")
            lines.append("            base_parameters:")
            for k, v in t["notebook_task"]["base_parameters"].items():
                lines.append(f"              {k}: \"{v}\"")
            lines.append("              catalog: ${var.catalog}")
            lines.append("          environment_key: wwi_serverless_env")
        lines.append(f"          max_retries: {t['max_retries']}")
        lines.append(f"          timeout_seconds: {t['timeout_seconds']}")
        lines.append("          retry_on_timeout: false")
    lines += [
        "      environments:",
        "        - environment_key: wwi_serverless_env",
        "          spec:",
        "            client: \"1\"",
        "            dependencies:",
        "              - delta-spark>=3.0.0",
    ]
    return "\n".join(lines)


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Generate a Databricks Asset Bundle job resource YAML from workflow_spec.json.",
    )
    p.add_argument("--input-path", metavar="DIR", default="./output",
                   help="Directory containing workflow_spec.json (default: ./output).")
    p.add_argument("--output-path", metavar="DIR", default="./bundle",
                   help="Directory to write the bundle resources into (default: ./bundle).")
    p.add_argument("--env", metavar="NAME", default="dev",
                   choices=["dev", "test", "prod"],
                   help="Target environment — substituted into catalog name (default: dev).")
    return p.parse_args()


_ENV_CATALOG = {"dev": "wwi_dev", "test": "wwi_test", "prod": "wwi_prod"}


def main() -> None:
    args = _parse_args()
    input_dir  = Path(args.input_path)
    output_dir = Path(args.output_path)

    workflow_spec_path = input_dir / "workflow_spec.json"
    if not workflow_spec_path.exists():
        print(f"error: workflow_spec.json not found in {input_dir}. "
              "Run run_ssis_conversion.py first.", file=sys.stderr)
        sys.exit(1)

    spec      = json.loads(workflow_spec_path.read_text(encoding="utf-8"))
    yaml_text = render_job_yaml(spec)
    yaml_text = yaml_text.replace("${var.catalog}", _ENV_CATALOG[args.env])

    resources_dir = output_dir / "resources"
    resources_dir.mkdir(parents=True, exist_ok=True)
    job_name = spec.get("name", "job")
    out_file = resources_dir / f"{job_name}.job.yml"
    out_file.write_text(yaml_text, encoding="utf-8")
    print(f"  ✓  {out_file}  ({len(spec['tasks'])} tasks, env={args.env})")
    print(f"\n  To deploy:")
    print(f"    databricks bundle validate --target {args.env}")
    print(f"    databricks bundle deploy  --target {args.env}")


if __name__ == "__main__":
    main()
