-- Source: DW:Integration.PopulateDateDimensionForYear  (/Users/shivaiyer/Documents/Claude/sql-server-samples/samples/databases/wide-world-importers/wwi-dw-ssdt/wwi-dw-ssdt/Integration/Stored Procedures/PopulateDateDimensionForYear.sql)
-- Split 1 of 2: SQL transformation logic extracted from an orchestration-heavy
-- stored procedure (rule: separate SQL transformation from workflow orchestration).
-- The CURSOR/WHILE control flow that drove row-by-row iteration in the source is
-- NOT reproduced here — see the companion PySpark orchestration file, which expresses
-- the same iteration as a set-based MERGE or a small parameterised loop.

INSERT Dimension.`Date`
                       ( `Date`
                       , `DateKey`
                       , [Day Number]
                       , `Day`
                       , [Day of Year]
                       , [Day of Year Number]
                       , [Day of Week]
                       , [Day of Week Number]
                       , [Week of Year]
                       , `Month`
                       , [Short Month]
                       , `Quarter`
                       , [Half of Year]
                       , [Beginning of Month]
                       , [Beginning of Quarter]
                       , [Beginning of Half Year]
                       , [Beginning of Year]
                       , [Beginning of Month Label]
                       , [Beginning of Month Label Short]
                       , [Beginning of Quarter Label]
                       , [Beginning of Quarter Label Short]
                       , [Beginning of Half Year Label]
                       , [Beginning of Half Year Label Short]
                       , [Beginning of Year Label]
                       , [Beginning of Year Label Short]
                       , [Calendar Day Label]
                       , [Calendar Day Label Short]
                       , [Calendar Week Number]
                       , [Calendar Week Label]
                       , [Calendar Month Number]
                       , [Calendar Month Label]
                       , [Calendar Month Year Label]
                       , [Calendar Quarter Number]
                       , [Calendar Quarter Label]
                       , [Calendar Quarter Year Label]
                       , [Calendar Half of Year Number]
                       , [Calendar Half of Year Label]
                       , [Calendar Year Half of Year Label]
                       , [Calendar Year]
                       , [Calendar Year Label]
                       , [Fiscal Month Number]
                       , [Fiscal Month Label]
                       , [Fiscal Quarter Number]
                       , [Fiscal Quarter Label]
                       , [Fiscal Half of Year Number]
                       , [Fiscal Half of Year Label]
                       , [Fiscal Year]
                       , [Fiscal Year Label]
                       , [Date Key]
                       , [Year Week Key]
                       , [Year Month Key]
                       , [Year Quarter Key]
                       , [Year Half of Year Key]
                       , [Year Key]
                       , [Beginning of Month Key]
                       , [Beginning of Quarter Key]
                       , [Beginning of Half Year Key]
                       , [Beginning of Year Key]
                       , [Fiscal Year Month Key]
                       , [Fiscal Year Quarter Key]
                       , [Fiscal Year Half of Year Key]
                       , [ISO Week Number]
                       )
                SELECT `Date`
                       , `DateKey`
                       , [Day Number]
                       , `Day`
                       , [Day of Year]
                       , [Day of Year Number]
                       , [Day of Week]
                       , [Day of Week Number]
                       , [Week of Year]
                       , `Month`
                       , [Short Month]
                       , `Quarter`
                       , [Half of Year]
                       , [Beginning of Month]
                       , [Beginning of Quarter]
                       , [Beginning of Half of Year]
                       , [Beginning of Year]
                       , [Beginning of Month Label]
                       , [Beginning of Month Label Short]
                       , [Beginning of Quarter Label]
                       , [Beginning of Quarter Label Short]
                       , [Beginning of Half Year Label]
                       , [Beginning of Half Year Label Short]
                       , [Beginning of Year Label]
                       , [Beginning of Year Label Short]
                       , [Calendar Day Label]
                       , [Calendar Day Label Short]
                       , [Calendar Week Number]
                       , [Calendar Week Label]
                       , [Calendar Month Number]
                       , [Calendar Month Label]
                       , [Calendar Month Year Label]
                       , [Calendar Quarter Number]
                       , [Calendar Quarter Label]
                       , [Calendar Quarter Year Label]
                       , [Calendar Half of Year Number]
                       , [Calendar Half of Year Label]
                       , [Calendar Year Half of Year Label]
                       , [Calendar Year]
                       , [Calendar Year Label]
                       , [Fiscal Month Number]
                       , [Fiscal Month Label]
                       , [Fiscal Quarter Number]
                       , [Fiscal Quarter Label]
                       , [Fiscal Half of Year Number]
                       , [Fiscal Half of Year Label]
                       , [Fiscal Year]
                       , [Fiscal Year Label]
                       , [Date Key]
                       , [Year Week Key]
                       , [Year Month Key]
                       , [Year Quarter Key]
                       , [Year Half of Year Key]
                       , [Year Key]
                       , [Beginning of Month Key]
                       , [Beginning of Quarter Key]
                       , [Beginning of Half of Year Key]
                       , [Beginning of Year Key]
                       , [Fiscal Year Month Key]
                       , [Fiscal Year Quarter Key]
                       , [Fiscal Year Half of Year Key]
                       , [ISO Week Number]
                    FROM Integration.GenerateDateDimensionColumns(@DateCounter);