"""
wwi_accelerator — shared runtime utilities for the converted PySpark/notebook
tasks under output/pyspark/ and output/ssis_tasks/.

This package is intentionally small: the bulk of the converted logic lives in
output/ (regenerated by run_conversion.py / run_ssis_conversion.py and
referenced directly by bundle/resources/*.job.yml via relative paths). This
package holds only cross-cutting helpers that every generated task needs —
environment/secret/catalog resolution — so that logic exists in exactly one
place instead of being duplicated across 60+ generated files.
"""

from .common import get_catalog, get_secret_scope, get_watermark, advance_watermark

__all__ = ["get_catalog", "get_secret_scope", "get_watermark", "advance_watermark"]
